# Generated by Django 6.0.5 on 2026-05-31 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Bank', 'Bank'), ('Insurance', 'Insurance')], default='Cash', max_length=20)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Fully Paid', 'Fully Paid')], default='Unpaid', max_length=20)),
                ('payment_note', models.CharField(blank=True, help_text='M-Pesa transaction codes, bank reference numbers, etc.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='opd.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originating_module', models.CharField(choices=[('Appointment', 'Appointment Fees'), ('OPD', 'OPD / Triage Consultation'), ('Laboratory', 'Laboratory Investigations'), ('Radiology', 'Radiology Scans'), ('Blood Bank', 'Blood Issues / Components'), ('Pharmacy', 'Pharmacy Dispensing')], max_length=30)),
                ('item_name', models.CharField(help_text='e.g., Full Blood Count, Paracetamol 500mg, Consultation', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage rate (e.g., 16.00 for 16% VAT)', max_digits=5)),
                ('row_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.billinginvoice')),
            ],
        ),
    ]
