# Generated by Django 6.0.5 on 2026-06-14 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Charge Category',
                'verbose_name_plural': 'Charge Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='payment_note',
            field=models.CharField(blank=True, help_text='M-Pesa codes, bank references, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='VAT percentage e.g. 16.00 for 16%', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.chargecategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
    ]
