# Generated by Django 6.0.5 on 2026-06-14 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_chargecategory_alter_billinginvoice_payment_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the insurance provider', max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short code (e.g. NHIF, SHA, JUBILEE)', max_length=50, null=True, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_empaneled', models.BooleanField(default=True, help_text='Hospital has active agreement with this provider')),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='insurance_approved_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount approved by insurance', max_digits=12),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='insurance_claim_number',
            field=models.CharField(blank=True, help_text='Claim reference number from insurance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='insurance_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.insuranceprovider'),
        ),
    ]
