# Generated by Django 6.0.5 on 2026-07-19 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0005_alter_patient_gender_alter_patient_marital_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='admitted', max_length=20)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('bed_number', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admission_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_admissions_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_patients', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipd_admissions', to='patients.patient')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
    ]
