# Generated by Django 6.0.5 on 2026-06-28 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='financepayment',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='financepayment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='created_by',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('payee_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Medical Supplies', 'Medical Supplies'), ('Laboratory Supplies', 'Laboratory Supplies'), ('Pharmacy', 'Pharmacy'), ('Equipment', 'Equipment'), ('Maintenance', 'Maintenance'), ('Utilities', 'Utilities'), ('Salaries', 'Salaries'), ('Administrative', 'Administrative'), ('Training', 'Training'), ('Transport', 'Transport'), ('Other', 'Other')], max_length=100)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_disbursed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('gl_code', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('row_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.expense')),
            ],
        ),
        migrations.DeleteModel(
            name='FinanceCategory',
        ),
        migrations.DeleteModel(
            name='FinancePayment',
        ),
        migrations.DeleteModel(
            name='FinanceTransaction',
        ),
    ]
