# Generated by Django 6.0.5 on 2026-06-29 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('laboratory', '0001_initial'),
        ('opd', '0002_patientvisit_applied_charge_and_more'),
        ('patients', '0005_alter_patient_gender_alter_patient_marital_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoryinvoice',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='laboratoryinvoiceitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='laboratorypayment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='laboratorytest',
            options={'ordering': ['-ordered_at']},
        ),
        migrations.RenameField(
            model_name='laboratoryinvoiceitem',
            old_name='test_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='laboratorypayment',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='laboratorytest',
            old_name='description',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='laboratorytest',
            old_name='created_at',
            new_name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoice',
            name='apply_insurance',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoice',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoice',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoice',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoice',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoice',
            name='patient_number',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoice',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoice',
            name='payment_note',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoice',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoiceitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoiceitem',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoiceitem',
            name='report_days',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvoiceitem',
            name='row_total',
        ),
        migrations.RemoveField(
            model_name='laboratorypayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='laboratorypayment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='laboratorytest',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='laboratorytest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='laboratorytest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='laboratorytest',
            name='tax_percent',
        ),
        migrations.AddField(
            model_name='laboratoryinvoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratoryinvoice',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratoryinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='laboratoryinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='laboratoryinvoice',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opd.patientvisit'),
        ),
        migrations.AddField(
            model_name='laboratoryinvoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='laboratoryinvoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='laboratoryinvoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='laboratoryinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='laboratorypayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('insurance', 'Insurance'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='normal_range',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_ordered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='performed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='test_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='test_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratoryinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='laboratoryinvoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='laboratoryinvoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laboratoryinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='laboratoryinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='laboratoryinvoice',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_invoices', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratoryinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='laboratoryinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='laboratoryinvoiceitem',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.laboratorytest'),
        ),
        migrations.AlterField(
            model_name='laboratorypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='laboratorypayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='laboratorypayment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_payments_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
