# Generated by Django 6.0.5 on 2026-06-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_laboratoryinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryinvoice',
            name='case_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laboratoryinvoice',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
