# Generated by Django 6.0.5 on 2026-07-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_laboratoryinvoice_case_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorytest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Test cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage', max_digits=5),
        ),
    ]
