from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

User = get_user_model()

class Stock(models.Model):
    """
    Tracks medicine inventory, shelf quantities, and baseline retail pricing 
    at the Eagles Mission Hospital pharmacy.
    """
    item_name = models.CharField(max_length=200, unique=True, db_index=True) # e.g., "Amoxicillin 500mg"
    generic_name = models.CharField(max_length=200, blank=True, null=True)
    batch_number = models.CharField(max_length=100, blank=True, null=True)
    
    # Inventory Parameters
    quantity_in_stock = models.PositiveIntegerField(default=0)
    reorder_level = models.PositiveIntegerField(default=10, help_text="Alert threshold to restock item")
    
    # Financial parameters
    buying_price = models.DecimalField(max_digits=10, decimal_places=2, help_text="Cost price per unit")
    selling_price = models.DecimalField(max_digits=10, decimal_places=2, help_text="Retail billing charge per unit")
    
    # Auditing
    expiry_date = models.DateField(db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def is_expired(self):
        return self.expiry_date <= timezone.now().date()

    @property
    def needs_restock(self):
        return self.quantity_in_stock <= self.reorder_level

    def __str__(self):
        return f"{self.item_name} ({self.quantity_in_stock} Units remaining)"


class Prescription(models.Model):
    """
    Master clinical container for a drug order. Generated by a clinician 
    and dispatched to the pharmacy using the Case ID.
    """
    STATUS_CHOICES = [
        ('Pending', 'Pending Dispensing'),
        ('Dispensed', 'Sent to Billing / Handed Over'),
        ('Cancelled', 'Cancelled / Adjusted'),
    ]

    # Hook explicitly onto our active OPD Encounter Case ID
    visit = models.ForeignKey(
        'opd.PatientVisit', 
        on_delete=models.PROTECT, 
        related_name='prescriptions'
    )
    
    # Track the staff member who authorized the medication sequence
    prescribed_by = models.ForeignKey(
        User, 
        on_delete=models.PROTECT, 
        related_name='issued_prescriptions'
    )
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    clinical_note = models.TextField(blank=True, null=True, help_text="Diagnosis context or special instructions")
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Rx for Case {self.visit.case_id} — {self.status}"


class PrescriptionItem(models.Model):
    """
    Line item matching individual drugs, dosages, and quantities ordered 
    within a master prescription request card.
    """
    prescription = models.ForeignKey(Prescription, on_delete=models.CASCADE, related_name='items')
    
    # Link back to our active stock pool to read real-time retail prices
    medicine = models.ForeignKey(Stock, on_delete=models.PROTECT, related_name='prescription_lines')
    
    # Clinical directions (e.g., "1 tab three times a day for 5 days = 15 total")
    dosage_instruction = models.CharField(max_length=255, help_text="e.g., 1x3 for 5 days")
    quantity_prescribed = models.PositiveIntegerField(default=1)
    quantity_dispensed = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.medicine.item_name} x {self.quantity_prescribed}"


class MedicinePurchase(models.Model):
    """
    Tracks external warehouse supply acquisitions and invoices 
    from wholesale pharmaceutical distributors.
    """
    purchase_number = models.CharField(max_length=50, unique=True, db_index=True) # e.g., PUR-2026-001
    purchase_date = models.DateField(default=timezone.now)
    supplier_bill_number = models.CharField(max_length=100) # e.g., INV-44012
    supplier_name = models.CharField(max_length=200, db_index=True) # e.g., Cosmos Limited
    
    # Financial breakdowns
    total_amount = models.DecimalField(max_digits=12, decimal_places=2)
    tax_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    discount_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    net_amount = models.DecimalField(max_digits=12, decimal_places=2)
    
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.purchase_number} - {self.supplier_name}"