# Generated by Django 6.0.5 on 2026-05-31 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Alert threshold to restock item')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Retail billing charge per unit', max_digits=10)),
                ('expiry_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending Dispensing'), ('Dispensed', 'Sent to Billing / Handed Over'), ('Cancelled', 'Cancelled / Adjusted')], default='Pending', max_length=20)),
                ('clinical_note', models.TextField(blank=True, help_text='Diagnosis context or special instructions', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='opd.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_instruction', models.CharField(help_text='e.g., 1x3 for 5 days', max_length=255)),
                ('quantity_prescribed', models.PositiveIntegerField(default=1)),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_lines', to='pharmacy.stock')),
            ],
        ),
    ]
