# Generated by Django 6.0.5 on 2026-06-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicinecategory_purchase_supplier_medicine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicinePurchase',
        ),
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'verbose_name_plural': 'Medicine Categories'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mrp',
            field=models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
