# Generated by Django 6.0.5 on 2026-06-14 19:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_delete_medicinepurchase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Medicine Categories'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Purchase Items'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['item_name'], 'verbose_name_plural': 'Stock Inventory'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AddField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Bank', 'Bank Transfer'), ('Credit', 'Credit')], default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='pharmacy.supplier'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='pharmacy.medicine'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum Retail Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='packing_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='row_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Retail billing charge per unit', max_digits=10),
        ),
    ]
