# Generated by Django 6.0.5 on 2026-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier_bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
