# Generated by Django 6.0.5 on 2026-06-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_gender_alter_patient_marital_status'),
        ('pharmacy', '0007_alter_purchase_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='case_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bills', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='prescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Bank', 'Bank Transfer'), ('Insurance', 'Insurance'), ('Credit', 'Credit')], default='Cash', max_length=50),
        ),
    ]
