# Generated by Django 6.0.5 on 2026-05-31 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('bp_systolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('bp_diastolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('current_stage', models.CharField(choices=[('Triage', 'In Triage'), ('Consultation', 'With Doctor'), ('Laboratory', 'Sent to Lab'), ('Radiology', 'Sent to X-Ray'), ('Pharmacy', 'Sent to Pharmacy'), ('Discharged', 'Discharged')], default='Triage', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
        ),
    ]
