# Generated by Django 6.0.5 on 2026-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Any known allergies (medication, food, environmental)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_id',
            field=models.CharField(blank=True, help_text='Insurance policy/membership number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, help_text='Insurance company name (e.g., NHIF, AAR, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_validity',
            field=models.DateField(blank=True, help_text='Insurance policy expiry date', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='remarks',
            field=models.TextField(blank=True, help_text='General observations or notes about the patient', null=True),
        ),
    ]
