"""
Django settings for nyangombe_main project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+a#u@xz+otakj!*^g-*7ykr8ae$rurz$1it470(2psg6oc32ty'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application Definition

INSTALLED_APPS = [
    # Core Django Framework Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local Clinical Modules (Your 12-App Ecosystem)
    'core',
    'accounts',
    'dashboard',
    'patients',
    'doctors',
    'pharmacy',
    'laboratory',
    'opd',
    'ipd',
    'billing',    
    'appointments',
    'radiology',
    'finance',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nyangombe_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Searches for global layout structures (base.html, sidebar.html)
        'DIRS': [BASE_DIR / 'templates'],
        # Crucial for isolated app templates (like accounts/login.html)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nyangombe_main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static Assets & Storage Management (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Locates developer-managed workspace styling rules inside nyangombehmsv2/static/
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Destination for automated system assets deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media Upload Management (Patient Records, Scans, Forms)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default Primary Key Auto Field Configuration

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================================================
# AUTHENTICATION REDIRECT PIPELINE
# ==========================================================================

# The view a user is kicked to if a @login_required decorator blocks them
LOGIN_URL = 'accounts:login'

# Where users landing patch immediately after typing valid credentials
LOGIN_REDIRECT_URL = 'dashboard:home'

# Sends users straight back to the login wall when they terminate their session
LOGOUT_REDIRECT_URL = 'accounts:login'

